
- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
  - include: tasks/ssh.yml
  - include: tasks/zsh.yml
  - include: tasks/node.yml
  - include: tasks/npm-packages.yml
  - include: tasks/program.yml
  - include: tasks/dotfiles.yml
  - include: tasks/mac.yml
    when: ansible_distribution == 'MacOSX'

